version: '3.7'
services:
  postgres:
    image: postgres
    container_name: postgres_inmana
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inmana_dev
    # volumes:
    #   - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: inmana-dev-db
